source 'https://rubygems.org'

gem 'github-pages', '>= 219', group: :jekyll_plugins

gem 'jekyll-redirect-from', '>= 0.16.0'

gem 'kramdown', '>= 2.3.1'

gem 'rexml', '>= 3.2.5'

gem 'activesupport', '>= 6.0.3.7'

gem 'execjs', '>= 2.8.1'

gem 'nokogiri', '>= 1.12.5'

gem 'rb-fsevent', '>= 0.11.0'

gem "addressable", ">= 2.8.0"
